name: Build and deploy

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: false
        default: 'develop'
        type: choice
        options:
          - develop
          - staging
          - production

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Declare variables
        id: variables
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push config
        uses: docker/build-push-action@v2
        with:
          context: config
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER_NAME }}/todo-app-nginx:latest,
            ${{ secrets.DOCKER_HUB_USER_NAME }}/todo-app-nginx:${{ steps.variables.outputs.hash }}

      - name: Pull image and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.API_HOST_USERNAME }}
          key: ${{ secrets.API_HOST_PRIVATE_KEY }}
          script: |
            docker stop todo-app-nginx; \
            docker run --rm --detach \
            --name=todo-app-nginx \
            --workdir=/app \
            --publish=80:80 \
            --env VERSION=${{ steps.variables.outputs.hash }} \
            lecovich/todo-app-nginx:${{ steps.variables.outputs.hash }} \
            nginx
